export const SET_TWEETS = 'SET_TWEETS'
export const FETCH_TWEETS = 'FETCH_TWEETS'
export const SET_LOADING_TWEETS_STATE = 'SET_LOADING_TWEETS_STATE'

export const SET_TRENDS = 'SET_TRENDS'
export const FETCH_TRENDS = 'FETCH_TRENDS'
export const SET_LOADING_TRENDS_STATE = 'SET_LOADING_TRENDS_STATE'

export const SET_TWEET_DATA = 'SET_TWEET_DATA'
export const FETCH_TWEET_DATA = 'FETCH_TWEET_DATA'
export const SET_LOADING_TWEET_STATE = 'SET_LOADING_TWEET_STATE'


export const FETCH_ADD_TWEET = 'FETCH_ADD_TWEET'
export const ADD_TWEET = 'ADD_TWEET'
export const SET_ADD_TWEET_STATE = 'SET_ADD_TWEET_STATE'

export const SET_WHO_FOLLOW = 'SET_WHO_FOLLOW'
export const FETCH_WHO_FOLLOW = 'FETCH_WHO_FOLLOW'
export const SET_LOADING_WHO_FOLLOW_STATE = 'SET_LOADING_WHO_FOLLOW_STATE'


export const LoadingState = {
  LOADED: 'LOADED',
  NEVER: 'NEVER',
  LOADING: 'LOADING',
  ERROR: 'ERROR'
}

export const addTweetState = {
  LOADED: 'LOADED',
  NEVER: 'NEVER',
  LOADING: 'LOADING',
  ERROR: 'ERROR'
}